theme: "hugo-resume-master"
# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Rodrigo Mahlmeister # Website name
baseurl: 'https://rodrigomahlmeister.com/' # Website URL
#copyright: '' # Footer text, e.g. '© {year} Me'

############################
## LANGUAGE
############################

#defaultContentLanguage: en
#hasCJKLanguage: false
#defaultContentLanguageInSubdir: false
#removePathAccents: true

############################
## MODULES
############################

#module:
  #imports:
   # - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
   #  - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## ADVANCED
############################

#enableGitInfo: false
#summaryLength: 30
#paginate: 5
#enableEmoji: true
#enableRobotsTXT: true
#footnotereturnlinkcontents: <sup>^</sup>
#ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
#permalinks:
 # event: '/talk/:slug/'
  #authors: '/author/:slug/'
  #tags: '/tag/:slug/'
  #categories: '/category/:slug/'
  #publication_types: '/publication-type/:slug/'
#disableAliases: true
#outputs:
  #home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  #section: [HTML, RSS]
#imaging:
  #resampleFilter: lanczos
  #quality: 75
  #anchor: smart
#timeout: 600000
#taxonomies:
  #tag: tags
  #category: categories
  #publication_type: publication_types
  #author: authors
#markup:
  #_merge: deep
#related:
  #threshold: 80
  #includeNewer: true
  #toLower: true
  #indices:
    #- name: tags
      #weight: 100
    #- name: categories
     # weight: 70
      
#params:
  #orgName: "Rodrigo Mahlmeister"
  #orgLocal: ""
  #description: "Personal website and portfolio of Rodrigo Mahlmeister"
  #twitter: "ro_mahl"

  # use a built-in color theme
  # one of: forest / grayscale / peach / plum /
  #         poppy / sky / violet / water
  #theme: "grayscale"

  # or, leave theme empty & make your own palette
  # see docs at https://hugo-apero.netlify.app/blog/color-themes/
  # the custom scss file must be in the assets/ folder
  # add the filename name here, without extension
  # to use hex colors instead of named tachyons colors, include "hex" in filename
  #custom_theme: "fb-hex"

  # use an embedded font-family
  # serif options: Fraunces / EB Garamond / Bitter
  # sans-serif options: Commissioner / Alegreya Sans / Metropolis
  # if you import your own fonts, name them here too
  #customtextFontFamily: "Ilisarniq-Light"
  #customheadingFontFamily: "Petrona"
  # alternatively, leave empty and select basic font options: sans-serif or serif
  # for more http://tachyons.io/docs/typography/font-family/
  #textFontFamily: "sans-serif"
  #headingFontFamily: "sans-serif"

languageCode: en-us
PygmentsCodeFences: true
PygmentsCodeFencesGuessSynta: true
PygmentsStyle: monokai
enableGitInfo: false

params:
address: Rollinsford, NH
email: rodrigosmahlmeister@gmail.com"
favicon: /favicon.ico
firstName: Eddie
lastName: Webb
profileImage: img/TechChat.png

showEducation: true
showExperience: true
showOpenSource: true
showProjects: true
showPublications: true
showQr: true
showSkills: true

params.google:

params.google.analytics:
trackerID: "XX-123446-01"

params.handles:
link: "https://www.linkedin.com/in/edwardwebb/"
name: "LinkedIn"

params.handles:
link: "https://github.com/eddiewebb/"
name: "GitHub"

params.handles:
link: "https://bitbucket.org/eddiewebb/"
name: "Bitbucket"

params.handles:
link: "https://stackoverflow.com/users/story/82880"
name: "Stack Overflow"

params.handles:
link: "https://keybase.io/edwardawebb"
name: "Keybase"

outputs:
home: ["HTML", "JSON"]

taxonomies:
tag: "tags"


